roles:
  - web: { description: 'web server' }
  - master_db: { description: 'master database' }
  - slave_db:  { description: 'slave database' }
  - memcached: { description: 'memcached' }
hosts:
  - web01: { ip: '192.168.1.10', roles: [ 'web', 'memcached' ], status: 'active' }
  - db01:  { ip: '192.168.1.50', roles: [ 'master_db' ], status: 'active' }
  - db02:  { ip: '192.168.1.60', roles: [ 'slave_db' ], status: 'active' }
  - db03:  { ip: '192.168.1.61', roles: [ 'slave_db' ], status: 'out' }
